test SwiftLint on CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -236,8 +236,8 @@ jobs:
           command: |
             /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
             brew install swiftlint
-            swiftlint lint --config swiftlint/.swiftlint.yml
-            if [ $? -eq 0 ]; then echo "SwiftLint passed."; else echo "SwiftLint failed." && cat "./swiftlint.log"; fi
+            swiftlint lint --config swiftlint/.swiftlint.yml || (echo "SwiftLint failed." && cat "./swiftlint.log" && exit 1)
+      echo "SwiftLint passed."
             
       - run:
           name: Build app and run unit-tests
