changes in SwiftLint CI check

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -237,7 +237,7 @@ jobs:
             /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
             brew install swiftlint
             swiftlint lint --config swiftlint/.swiftlint.yml
-            if [ -f "./swiftlint.log" ]; then echo "SwiftLint failed." && cat "./swiftlint.log" && exit 1; else echo "SwiftLint passed."; fi
+            if [ $? -eq 0 ]; then echo "SwiftLint passed."; else echo "SwiftLint failed." && cat "./swiftlint.log"; fi
             
       - run:
           name: Build app and run unit-tests
